// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFF_wtP_oYpbYQ9CIkvFphNG6uqTOb2mU',
    appId: '1:2918996686:web:b721fcd574a9c548054e9f',
    messagingSenderId: '2918996686',
    projectId: 'actmgr-9b618',
    authDomain: 'actmgr-9b618.firebaseapp.com',
    storageBucket: 'actmgr-9b618.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW7SNea884U6t6zzyCA_U3NGp3SfAJxww',
    appId: '1:2918996686:android:3558a2bef2782fb8054e9f',
    messagingSenderId: '2918996686',
    projectId: 'actmgr-9b618',
    storageBucket: 'actmgr-9b618.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBacdVo_U7DG8NQXchPiYCkA5eX-ljVC1Y',
    appId: '1:2918996686:ios:4a45845c410074ee054e9f',
    messagingSenderId: '2918996686',
    projectId: 'actmgr-9b618',
    storageBucket: 'actmgr-9b618.firebasestorage.app',
    iosBundleId: 'com.example.rukoMobileApp',
  );

}